[variables]
COREPACK_INTEGRITY_KEYS = "0"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install -g pnpm@9.15.9",
  "pnpm install --frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build:cms"]

[start]
cmd = "node apps/api/dist/server.js"
